/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2025-01-07 04:59:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244278716L));
    _jspx_dependants.put("jar:file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /checkout.jsp(5,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /checkout.jsp(6,2) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    <!-- Single Page Header start -->\r\n");
      out.write("    <div class=\"container-fluid page-header py-5\">\r\n");
      out.write("      <h1 class=\"text-center text-white display-6\">Checkout</h1>\r\n");
      out.write("      <ol class=\"breadcrumb justify-content-center mb-0\">\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"#\">Pages</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item active text-white\">Checkout</li>\r\n");
      out.write("      </ol>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Single Page Header End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Checkout Page Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("      <div class=\"container py-5\">\r\n");
      out.write("        <h1 class=\"mb-4\">Billing details</h1>\r\n");
      out.write("        <form action=\"#\">\r\n");
      out.write("          <div class=\"row g-5\">\r\n");
      out.write("            <div class=\"col-md-12 col-lg-6 col-xl-7\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("                  <div class=\"form-item w-100\">\r\n");
      out.write("                    <label class=\"form-label my-3\">First Name<sup>*</sup></label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("                  <div class=\"form-item w-100\">\r\n");
      out.write("                    <label class=\"form-label my-3\">Last Name<sup>*</sup></label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <label class=\"form-label my-3\">Company Name<sup>*</sup></label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <label class=\"form-label my-3\">Address <sup>*</sup></label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"House Number Street Name\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <label class=\"form-label my-3\">Town/City<sup>*</sup></label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <label class=\"form-label my-3\">Country<sup>*</sup></label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <label class=\"form-label my-3\">Postcode/Zip<sup>*</sup></label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <label class=\"form-label my-3\">Mobile<sup>*</sup></label>\r\n");
      out.write("                <input type=\"tel\" class=\"form-control\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <label class=\"form-label my-3\">Email Address<sup>*</sup></label>\r\n");
      out.write("                <input type=\"email\" class=\"form-control\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-check my-3\">\r\n");
      out.write("                <input type=\"checkbox\" class=\"form-check-input\" id=\"Account-1\" name=\"Accounts\" value=\"Accounts\">\r\n");
      out.write("                <label class=\"form-check-label\" for=\"Account-1\">Create an account?</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <hr>\r\n");
      out.write("              <div class=\"form-check my-3\">\r\n");
      out.write("                <input class=\"form-check-input\" type=\"checkbox\" id=\"Address-1\" name=\"Address\" value=\"Address\">\r\n");
      out.write("                <label class=\"form-check-label\" for=\"Address-1\">Ship to a different address?</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-item\">\r\n");
      out.write("                <textarea name=\"text\" class=\"form-control\" spellcheck=\"false\" cols=\"30\" rows=\"11\" placeholder=\"Oreder Notes (Optional)\"></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-12 col-lg-6 col-xl-5\">\r\n");
      out.write("              <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th scope=\"col\">Products</th>\r\n");
      out.write("                    <th scope=\"col\">Name</th>\r\n");
      out.write("                    <th scope=\"col\">Price</th>\r\n");
      out.write("                    <th scope=\"col\">Quantity</th>\r\n");
      out.write("                    <th scope=\"col\">Total</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th scope=\"row\">\r\n");
      out.write("                      <div class=\"d-flex align-items-center mt-2\">\r\n");
      out.write("                        <img src=\"img/vegetable-item-2.jpg\" class=\"img-fluid rounded-circle\" style=\"width: 90px; height: 90px;\" alt=\"\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <td class=\"py-5\">Awesome Brocoli</td>\r\n");
      out.write("                    <td class=\"py-5\">$69.00</td>\r\n");
      out.write("                    <td class=\"py-5\">2</td>\r\n");
      out.write("                    <td class=\"py-5\">$138.00</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th scope=\"row\">\r\n");
      out.write("                      <div class=\"d-flex align-items-center mt-2\">\r\n");
      out.write("                        <img src=\"img/vegetable-item-5.jpg\" class=\"img-fluid rounded-circle\" style=\"width: 90px; height: 90px;\" alt=\"\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <td class=\"py-5\">Potatoes</td>\r\n");
      out.write("                    <td class=\"py-5\">$69.00</td>\r\n");
      out.write("                    <td class=\"py-5\">2</td>\r\n");
      out.write("                    <td class=\"py-5\">$138.00</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th scope=\"row\">\r\n");
      out.write("                      <div class=\"d-flex align-items-center mt-2\">\r\n");
      out.write("                        <img src=\"img/vegetable-item-3.png\" class=\"img-fluid rounded-circle\" style=\"width: 90px; height: 90px;\" alt=\"\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <td class=\"py-5\">Big Banana</td>\r\n");
      out.write("                    <td class=\"py-5\">$69.00</td>\r\n");
      out.write("                    <td class=\"py-5\">2</td>\r\n");
      out.write("                    <td class=\"py-5\">$138.00</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th scope=\"row\">\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <td class=\"py-5\"></td>\r\n");
      out.write("                    <td class=\"py-5\"></td>\r\n");
      out.write("                    <td class=\"py-5\">\r\n");
      out.write("                      <p class=\"mb-0 text-dark py-3\">Subtotal</p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"py-5\">\r\n");
      out.write("                      <div class=\"py-3 border-bottom border-top\">\r\n");
      out.write("                        <p class=\"mb-0 text-dark\">$414.00</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th scope=\"row\">\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <td class=\"py-5\">\r\n");
      out.write("                      <p class=\"mb-0 text-dark py-4\">Shipping</p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td colspan=\"3\" class=\"py-5\">\r\n");
      out.write("                      <div class=\"form-check text-start\">\r\n");
      out.write("                        <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Shipping-1\" name=\"Shipping-1\" value=\"Shipping\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"Shipping-1\">Free Shipping</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check text-start\">\r\n");
      out.write("                        <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Shipping-2\" name=\"Shipping-1\" value=\"Shipping\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"Shipping-2\">Flat rate: $15.00</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-check text-start\">\r\n");
      out.write("                        <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Shipping-3\" name=\"Shipping-1\" value=\"Shipping\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"Shipping-3\">Local Pickup: $8.00</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th scope=\"row\">\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <td class=\"py-5\">\r\n");
      out.write("                      <p class=\"mb-0 text-dark text-uppercase py-3\">TOTAL</p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"py-5\"></td>\r\n");
      out.write("                    <td class=\"py-5\"></td>\r\n");
      out.write("                    <td class=\"py-5\">\r\n");
      out.write("                      <div class=\"py-3 border-bottom border-top\">\r\n");
      out.write("                        <p class=\"mb-0 text-dark\">$135.00</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row g-4 text-center align-items-center justify-content-center border-bottom py-3\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div class=\"form-check text-start my-3\">\r\n");
      out.write("                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Transfer-1\" name=\"Transfer\" value=\"Transfer\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"Transfer-1\">Direct Bank Transfer</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"text-start text-dark\">Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row g-4 text-center align-items-center justify-content-center border-bottom py-3\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div class=\"form-check text-start my-3\">\r\n");
      out.write("                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Payments-1\" name=\"Payments\" value=\"Payments\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"Payments-1\">Check Payments</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row g-4 text-center align-items-center justify-content-center border-bottom py-3\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div class=\"form-check text-start my-3\">\r\n");
      out.write("                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Delivery-1\" name=\"Delivery\" value=\"Delivery\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"Delivery-1\">Cash On Delivery</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row g-4 text-center align-items-center justify-content-center border-bottom py-3\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div class=\"form-check text-start my-3\">\r\n");
      out.write("                    <input type=\"checkbox\" class=\"form-check-input bg-primary border-0\" id=\"Paypal-1\" name=\"Paypal\" value=\"Paypal\">\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"Paypal-1\">Paypal</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row g-4 text-center align-items-center justify-content-center pt-4\">\r\n");
      out.write("                <button type=\"button\" class=\"btn border-secondary py-3 px-4 text-uppercase w-100 text-primary\">Place Order</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Checkout Page End -->\r\n");
      out.write("  ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
