/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2025-01-06 18:04:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class store_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244278716L));
    _jspx_dependants.put("jar:file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /store.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /store.jsp(4,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <!-- Single Page Header start -->\r\n");
      out.write("        <div class=\"container-fluid page-header py-5\">\r\n");
      out.write("            <h1 class=\"text-center text-white display-6\">Shop</h1>\r\n");
      out.write("            <ol class=\"breadcrumb justify-content-center mb-0\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Pages</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active text-white\">Shop</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Single Page Header End -->\r\n");
      out.write("        <!-- Fruits Shop Start-->\r\n");
      out.write("        <div class=\"container-fluid fruite py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <h1 class=\"mb-4\">Fresh fruits shop</h1>\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"row g-4\">\r\n");
      out.write("                            <div class=\"col-xl-3\">\r\n");
      out.write("                                <div class=\"input-group w-100 mx-auto d-flex\">\r\n");
      out.write("                                    <input type=\"search\" class=\"form-control p-3\" placeholder=\"keywords\" aria-describedby=\"search-icon-1\">\r\n");
      out.write("                                    <span id=\"search-icon-1\" class=\"input-group-text p-3\"><i class=\"fa fa-search\"></i></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-6\"></div>\r\n");
      out.write("                            <div class=\"col-xl-3\">\r\n");
      out.write("                                <div class=\"bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4\">\r\n");
      out.write("                                    <label for=\"fruits\">Default Sorting:</label>\r\n");
      out.write("                                    <select id=\"fruits\" name=\"fruitlist\" class=\"border-0 form-select-sm bg-light me-3\" form=\"fruitform\">\r\n");
      out.write("                                        <option value=\"volvo\">Nothing</option>\r\n");
      out.write("                                        <option value=\"saab\">Popularity</option>\r\n");
      out.write("                                        <option value=\"opel\">Organic</option>\r\n");
      out.write("                                        <option value=\"audi\">Fantastic</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row g-4\">\r\n");
      out.write("                            <div class=\"col-lg-3\">\r\n");
      out.write("                                <div class=\"row g-4\">\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <div class=\"mb-3\">\r\n");
      out.write("                                            <h4>Categories</h4>\r\n");
      out.write("                                            <ul class=\"list-unstyled fruite-categorie\">\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <div class=\"d-flex justify-content-between fruite-name\">\r\n");
      out.write("                                                        <a href=\"#\"><i class=\"fas fa-apple-alt me-2\"></i>Apples</a>\r\n");
      out.write("                                                        <span>(3)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <div class=\"d-flex justify-content-between fruite-name\">\r\n");
      out.write("                                                        <a href=\"#\"><i class=\"fas fa-apple-alt me-2\"></i>Oranges</a>\r\n");
      out.write("                                                        <span>(5)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <div class=\"d-flex justify-content-between fruite-name\">\r\n");
      out.write("                                                        <a href=\"#\"><i class=\"fas fa-apple-alt me-2\"></i>Strawbery</a>\r\n");
      out.write("                                                        <span>(2)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <div class=\"d-flex justify-content-between fruite-name\">\r\n");
      out.write("                                                        <a href=\"#\"><i class=\"fas fa-apple-alt me-2\"></i>Banana</a>\r\n");
      out.write("                                                        <span>(8)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <div class=\"d-flex justify-content-between fruite-name\">\r\n");
      out.write("                                                        <a href=\"#\"><i class=\"fas fa-apple-alt me-2\"></i>Pumpkin</a>\r\n");
      out.write("                                                        <span>(5)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <div class=\"mb-3\">\r\n");
      out.write("                                            <h4 class=\"mb-2\">Price</h4>\r\n");
      out.write("                                            <input type=\"range\" class=\"form-range w-100\" id=\"rangeInput\" name=\"rangeInput\" min=\"0\" max=\"500\" value=\"0\" oninput=\"amount.value=rangeInput.value\">\r\n");
      out.write("                                            <output id=\"amount\" name=\"amount\" min-velue=\"0\" max-value=\"500\" for=\"rangeInput\">0</output>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <div class=\"mb-3\">\r\n");
      out.write("                                            <h4>Additional</h4>\r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <input type=\"radio\" class=\"me-2\" id=\"Categories-1\" name=\"Categories-1\" value=\"Beverages\">\r\n");
      out.write("                                                <label for=\"Categories-1\"> Organic</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <input type=\"radio\" class=\"me-2\" id=\"Categories-2\" name=\"Categories-1\" value=\"Beverages\">\r\n");
      out.write("                                                <label for=\"Categories-2\"> Fresh</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <input type=\"radio\" class=\"me-2\" id=\"Categories-3\" name=\"Categories-1\" value=\"Beverages\">\r\n");
      out.write("                                                <label for=\"Categories-3\"> Sales</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <input type=\"radio\" class=\"me-2\" id=\"Categories-4\" name=\"Categories-1\" value=\"Beverages\">\r\n");
      out.write("                                                <label for=\"Categories-4\"> Discount</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"mb-2\">\r\n");
      out.write("                                                <input type=\"radio\" class=\"me-2\" id=\"Categories-5\" name=\"Categories-1\" value=\"Beverages\">\r\n");
      out.write("                                                <label for=\"Categories-5\"> Expired</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <h4 class=\"mb-3\">Featured products</h4>\r\n");
      out.write("                                        <div class=\"d-flex align-items-center justify-content-start\">\r\n");
      out.write("                                            <div class=\"rounded me-4\" style=\"width: 100px; height: 100px;\">\r\n");
      out.write("                                                <img src=\"img/featur-1.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h6 class=\"mb-2\">Big Banana</h6>\r\n");
      out.write("                                                <div class=\"d-flex mb-2\">\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"d-flex mb-2\">\r\n");
      out.write("                                                    <h5 class=\"fw-bold me-2\">2.99 $</h5>\r\n");
      out.write("                                                    <h5 class=\"text-danger text-decoration-line-through\">4.11 $</h5>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"d-flex align-items-center justify-content-start\">\r\n");
      out.write("                                            <div class=\"rounded me-4\" style=\"width: 100px; height: 100px;\">\r\n");
      out.write("                                                <img src=\"img/featur-2.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h6 class=\"mb-2\">Big Banana</h6>\r\n");
      out.write("                                                <div class=\"d-flex mb-2\">\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"d-flex mb-2\">\r\n");
      out.write("                                                    <h5 class=\"fw-bold me-2\">2.99 $</h5>\r\n");
      out.write("                                                    <h5 class=\"text-danger text-decoration-line-through\">4.11 $</h5>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"d-flex align-items-center justify-content-start\">\r\n");
      out.write("                                            <div class=\"rounded me-4\" style=\"width: 100px; height: 100px;\">\r\n");
      out.write("                                                <img src=\"img/featur-3.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h6 class=\"mb-2\">Big Banana</h6>\r\n");
      out.write("                                                <div class=\"d-flex mb-2\">\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"d-flex mb-2\">\r\n");
      out.write("                                                    <h5 class=\"fw-bold me-2\">2.99 $</h5>\r\n");
      out.write("                                                    <h5 class=\"text-danger text-decoration-line-through\">4.11 $</h5>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center my-4\">\r\n");
      out.write("                                            <a href=\"#\" class=\"btn border border-secondary px-4 py-3 rounded-pill text-primary w-100\">Vew More</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <div class=\"position-relative\">\r\n");
      out.write("                                            <img src=\"img/banner-fruits.jpg\" class=\"img-fluid w-100 rounded\" alt=\"\">\r\n");
      out.write("                                            <div class=\"position-absolute\" style=\"top: 50%; right: 10px; transform: translateY(-50%);\">\r\n");
      out.write("                                                <h3 class=\"text-secondary fw-bold\">Fresh <br> Fruits <br> Banner</h3>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-9\">\r\n");
      out.write("                                <div class=\"row g-4 justify-content-center\">\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-5.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Grapes</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-5.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Grapes</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-2.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Raspberries</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-4.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Apricots</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-3.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Banana</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-1.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Oranges</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-2.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Raspberries</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-5.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Grapes</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-1.jpg\" class=\"img-fluid w-100 rounded-top\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\" style=\"top: 10px; left: 10px;\">Fruits</div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Oranges</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <div class=\"pagination d-flex justify-content-center mt-5\">\r\n");
      out.write("                                            <a href=\"#\" class=\"rounded\">&laquo;</a>\r\n");
      out.write("                                            <a href=\"#\" class=\"active rounded\">1</a>\r\n");
      out.write("                                            <a href=\"#\" class=\"rounded\">2</a>\r\n");
      out.write("                                            <a href=\"#\" class=\"rounded\">3</a>\r\n");
      out.write("                                            <a href=\"#\" class=\"rounded\">4</a>\r\n");
      out.write("                                            <a href=\"#\" class=\"rounded\">5</a>\r\n");
      out.write("                                            <a href=\"#\" class=\"rounded\">6</a>\r\n");
      out.write("                                            <a href=\"#\" class=\"rounded\">&raquo;</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Fruits Shop End-->\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
