/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2025-01-15 07:45:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Yasiru%20Kavinda/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244278716L));
    _jspx_dependants.put("file:/C:/Users/Yasiru%20Kavinda/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar", Long.valueOf(1735630431522L));
    _jspx_dependants.put("jar:file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/frontend/cart.jsp(4,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user eq null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    boolean _jspx_th_c_005fredirect_005f0_reused = false;
    try {
      _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fredirect_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/frontend/cart.jsp(5,4) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fredirect_005f0.setUrl("login");
      int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
      if (_jspx_th_c_005fredirect_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      _jspx_th_c_005fredirect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fredirect_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fredirect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/cart.jsp(8,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/cart.jsp(9,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/cart.jsp(190,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("script");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <!-- Single Page Header start -->\r\n");
      out.write("        <div class=\"container-fluid page-header py-5\">\r\n");
      out.write("            <h1 class=\"text-center text-white display-6\">Cart</h1>\r\n");
      out.write("            <ol class=\"breadcrumb justify-content-center mb-0\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Pages</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active text-white\">Cart</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Single Page Header End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Cart Page Start -->\r\n");
      out.write("        <div class=\"container-fluid py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th class=\"product-image\" scope=\"col\">Products</th>\r\n");
      out.write("                            <th class=\"product-name\" scope=\"col\">Name</th>\r\n");
      out.write("                            <th class=\"product-price\" scope=\"col\">Price</th>\r\n");
      out.write("                            <th class=\"product-quantity\" scope=\"col\">Quantity</th>\r\n");
      out.write("                            <th class=\"product-total\" scope=\"col\">Total</th>\r\n");
      out.write("                            <th class=\"product-action\" scope=\"col\">Handle</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody id=\"cart-container\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row mt-6 g-4 justify-content-end\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-sm-4 col-md-5 col-lg-6 col-xl-8 sticky-sidebar-wrapper\">\r\n");
      out.write("                        <div class=\"sticky-sidebar\">\r\n");
      out.write("                            <div class=\"cart-summary mb-4\">\r\n");
      out.write("                                <h3 class=\"cart-title text-uppercase\">Invoice Details</h3>\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("                                    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <hr class=\"divider\">\r\n");
      out.write("\r\n");
      out.write("                                <ul class=\"shipping-methods mb-2\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <label\r\n");
      out.write("                                                class=\"shipping-title text-dark font-weight-bold\">Payment\r\n");
      out.write("                                            Method</label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"custom-radio mt-2\">\r\n");
      out.write("                                            <input type=\"radio\" id=\"card-payment\" class=\"custom-control-input\"\r\n");
      out.write("                                                   name=\"pay\" value=\"card\" checked>\r\n");
      out.write("                                            <label for=\"card-payment\" class=\"custom-control-label color-dark\">\r\n");
      out.write("                                                Card Payment\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"custom-radio mt-2\">\r\n");
      out.write("                                            <input type=\"radio\" id=\"cod\" class=\"custom-control-input\"\r\n");
      out.write("                                                   name=\"pay\" value=\"cod\">\r\n");
      out.write("                                            <label for=\"cod\" class=\"custom-control-label color-dark\">\r\n");
      out.write("                                                Cash On Delivery\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"shipping-calculator mt-4\">\r\n");
      out.write("                                    <p class=\"shipping-destination lh-1\">Shipping to <strong>LK</strong>.</p>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"shipping-calculator-form\">\r\n");
      out.write("                                        <div class=\"form-group mt-3\">\r\n");
      out.write("                                            <input class=\"form-control form-control-md\" type=\"text\"\r\n");
      out.write("                                                   id=\"cityElement\" placeholder=\"Town / City\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group mt-3\">\r\n");
      out.write("                                            <input class=\"form-control form-control-md\" type=\"text\"\r\n");
      out.write("                                                   id=\"streetElement\" placeholder=\"Street\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group mt-3\">\r\n");
      out.write("                                            <input class=\"form-control form-control-md\" type=\"text\"\r\n");
      out.write("                                                   id=\"zipcodeElement\" placeholder=\"ZIP\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                            ");
      out.write("\r\n");
      out.write("                                            ");
      out.write("\r\n");
      out.write("                                            ");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-sm-8 col-md-7 col-lg-6 col-xl-4\">\r\n");
      out.write("                        <div class=\"bg-light rounded\">\r\n");
      out.write("                            <div class=\"p-4\">\r\n");
      out.write("                                <h1 class=\"display-6 mb-4\">Cart <span class=\"fw-normal\">Total</span></h1>\r\n");
      out.write("                                <div class=\"d-flex justify-content-between mb-4\">\r\n");
      out.write("                                    <h5 class=\"mb-0 me-4\">Subtotal:</h5>\r\n");
      out.write("                                    <p class=\"mb-0\" id=\"subTotal\">LKR 0.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                    <h5 class=\"mb-0 me-4\">Shipping</h5>\r\n");
      out.write("                                    <div class=\"\">\r\n");
      out.write("                                        <p class=\"mb-0\" id=\"deliveryCost\">LKR 0.00</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"py-4 mb-4 border-top border-bottom d-flex justify-content-between\">\r\n");
      out.write("                                <h5 class=\"mb-0 ps-4 me-4\">Total</h5>\r\n");
      out.write("                                <p class=\"mb-0 pe-4 \" id=\"finalTotal\">LKR 0.00</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button class=\"btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4\"\r\n");
      out.write("                                    type=\"button\" onclick=\"onClickCheckout()\">Proceed Checkout\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Cart Page End -->\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"https://www.payhere.lk/lib/payhere.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            fetchCartData();\r\n");
      out.write("\r\n");
      out.write("            function fetchCartData() {\r\n");
      out.write("                secureFetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/cart\")\r\n");
      out.write("                    .then(async response => {\r\n");
      out.write("                        if (response.ok) {\r\n");
      out.write("                            return await response.json();\r\n");
      out.write("                        } else\r\n");
      out.write("                            return null;\r\n");
      out.write("                    })\r\n");
      out.write("                    .then(\r\n");
      out.write("                        async data => {\r\n");
      out.write("                            if (data) {\r\n");
      out.write("                                listCartItems(data?.data);\r\n");
      out.write("                                calculateTotals(data?.data)\r\n");
      out.write("                            }else\r\n");
      out.write("                                window.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login\";\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    );\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            function listCartItems(data) {\r\n");
      out.write("                const table = document.getElementById(\"cart-container\");\r\n");
      out.write("                table.innerHTML = \"\";\r\n");
      out.write("                if (data?.length > 0) {\r\n");
      out.write("                    data.forEach(item => {\r\n");
      out.write("                        let row = table.insertRow();\r\n");
      out.write("                        let cell = row.insertCell();\r\n");
      out.write("                        let productPrice = item.stockDAO?.price ?? 0;\r\n");
      out.write("                        let qty = item?.quantity ?? 0;\r\n");
      out.write("                        let cartId = item?.id;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        cell.classList.add(\"product-image\");\r\n");
      out.write("\r\n");
      out.write("                        cell.innerHTML = `\r\n");
      out.write("                         <p class=\"mb-0 mt-4\">\r\n");
      out.write("                                   ` + (item?.id) + `\r\n");
      out.write("                         </p>\r\n");
      out.write("                        `;\r\n");
      out.write("                        cell = row.insertCell();\r\n");
      out.write("                        cell.classList.add(\"product-name\");\r\n");
      out.write("                        cell.innerHTML = `\r\n");
      out.write("                            <p class=\"mb-0 mt-4\">` + (item?.stockDAO?.productByProductId?.name) + `</p>\r\n");
      out.write("                        `;\r\n");
      out.write("                        cell = row.insertCell();\r\n");
      out.write("                        cell.classList.add(\"product-price\");\r\n");
      out.write("                        cell.innerHTML = `\r\n");
      out.write("                         <p class=\"mb-0 mt-4\">`+(parseFloat(item?.stockDAO?.price).toFixed(2))+`</p>\r\n");
      out.write("                        `;\r\n");
      out.write("\r\n");
      out.write("                        cell = row.insertCell();\r\n");
      out.write("                        cell.classList.add(\"product-quantity\");\r\n");
      out.write("                        cell.innerHTML = `\r\n");
      out.write("                                <div class=\"input-group quantity mt-4\" style=\"width: 100px;\">\r\n");
      out.write("                                    <div class=\"input-group-btn\">\r\n");
      out.write("                                        <button class=\"btn btn-sm btn-minus rounded-circle bg-light border\" onclick=\"minusQuantity(` + item.id + `,` + qty + `)\">\r\n");
      out.write("                                            <i class=\"fa fa-minus\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control form-control-sm text-center border-0\" value=\"`+Number(qty)+`\" disabled>\r\n");
      out.write("                                    <div class=\"input-group-btn\">\r\n");
      out.write("                                        <button class=\"btn btn-sm btn-plus rounded-circle bg-light border\" onclick=\"plusQuantity(` + item.id + `,` + qty + `);\">\r\n");
      out.write("                                            <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        `;\r\n");
      out.write("\r\n");
      out.write("                        cell = row.insertCell();\r\n");
      out.write("                        cell.classList.add(\"product-total\");\r\n");
      out.write("                        cell.innerHTML = `\r\n");
      out.write("                                <p class=\"mb-0 mt-4\">LKR `+parseFloat(item?.stockDAO?.price*qty).toFixed(2)+`</p>\r\n");
      out.write("                        `;\r\n");
      out.write("\r\n");
      out.write("                        cell = row.insertCell();\r\n");
      out.write("                        cell.classList.add(\"product-action\");\r\n");
      out.write("                        cell.innerHTML = `\r\n");
      out.write("                         <button class=\"btn btn-md rounded-circle bg-light border mt-4\" onclick=\"removeItemFromCart(`+item.id+`);\">\r\n");
      out.write("                                                                <i class=\"fa fa-times text-danger\"></i>\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                        `\r\n");
      out.write("\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                }else{\r\n");
      out.write("                    let row = table.insertRow();\r\n");
      out.write("                    let cell = row.insertCell();\r\n");
      out.write("                    cell.classList.add(\"product-name\");\r\n");
      out.write("                    cell.classList.add(\"text-center\");\r\n");
      out.write("                    cell.colSpan = 4;\r\n");
      out.write("                    cell.innerHTML= \"No Cart Items Available\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function calculateTotals(data){\r\n");
      out.write("                const subTotalElement = document.getElementById(\"subTotal\");\r\n");
      out.write("                const deliveryCostElement = document.getElementById(\"deliveryCost\");\r\n");
      out.write("                const total = document.getElementById(\"finalTotal\");\r\n");
      out.write("\r\n");
      out.write("                const DELIVERY_COST = 600;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                let subTotal = 0;\r\n");
      out.write("                let finalTotal = 0;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                if(data?.length){\r\n");
      out.write("                    data.forEach(item=>{\r\n");
      out.write("                        let qty = item?.quantity;\r\n");
      out.write("                        subTotal += (item?.stockDAO?.price ?? 0) * qty;\r\n");
      out.write("                        finalTotal += (item?.stockDAO?.price ? (item?.stockDAO?.price * qty): 0);\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    finalTotal+= DELIVERY_COST;\r\n");
      out.write("\r\n");
      out.write("                    const CURRENCY_TAG = \"Rs. \";\r\n");
      out.write("\r\n");
      out.write("                    subTotalElement.innerHTML = CURRENCY_TAG+parseFloat(subTotal).toFixed(2);\r\n");
      out.write("                    deliveryCostElement.innerHTML = CURRENCY_TAG + parseFloat(DELIVERY_COST).toFixed(2);\r\n");
      out.write("                    total.innerHTML = CURRENCY_TAG + parseFloat(finalTotal).toFixed(2);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                }else{\r\n");
      out.write("                    subTotalElement.innerHTML = \"\";\r\n");
      out.write("                    deliveryCostElement.innerHTML = \"\";\r\n");
      out.write("                    total.innerHTML = \"\";\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function onClickCheckout(){\r\n");
      out.write("                const city = document.getElementById(\"cityElement\").value;\r\n");
      out.write("                const street = document.getElementById(\"streetElement\").value;\r\n");
      out.write("                const zipcode = document.getElementById(\"zipcodeElement\").value;\r\n");
      out.write("                const paymentMethod = document.querySelector(\"input[name='pay']:checked\").value;\r\n");
      out.write("                console.log(paymentMethod);\r\n");
      out.write("\r\n");
      out.write("                if(!city || !city.trim()|| !street||!street.trim()||!zipcode||!zipcode.trim()){\r\n");
      out.write("                    alert(\"shipping adress is compulsory to fill  in\");\r\n");
      out.write("                }else{\r\n");
      out.write("\r\n");
      out.write("                    const addressDetails = {\r\n");
      out.write("                        city,\r\n");
      out.write("                        street,\r\n");
      out.write("                        zipcode,\r\n");
      out.write("                        paymentMethod\r\n");
      out.write("                    };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    secureFetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/orders/cart/on-checkout\")\r\n");
      out.write("                        .then(async response => {\r\n");
      out.write("                            if (response.ok) {\r\n");
      out.write("                                return await response.json();\r\n");
      out.write("                            } else\r\n");
      out.write("                                return null;\r\n");
      out.write("                        })\r\n");
      out.write("                        .then(async data => {\r\n");
      out.write("                            if (data) {\r\n");
      out.write("                                if (paymentMethod === \"card\")\r\n");
      out.write("                                    initCardPayment(data?.data ?? null, addressDetails);\r\n");
      out.write("                                else\r\n");
      out.write("                                    saveCartOrder(data?.data ?? null, addressDetails);\r\n");
      out.write("                            } else {\r\n");
      out.write("                                alert(\"Checkout failed\");\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            function initCardPayment(data, addressDetails) {\r\n");
      out.write("                if (data && addressDetails) {\r\n");
      out.write("                    alert(data.hash);\r\n");
      out.write("                    console.log(data);\r\n");
      out.write("                    console.log(addressDetails);\r\n");
      out.write("\r\n");
      out.write("                    payhere.onCompleted = function onCompleted(orderId) {\r\n");
      out.write("                        console.log(\"Payment completed. OrderID:\" + orderId);\r\n");
      out.write("\r\n");
      out.write("                        saveCartOrder(data, addressDetails);\r\n");
      out.write("                    };\r\n");
      out.write("\r\n");
      out.write("                    // Payment window closed\r\n");
      out.write("                    payhere.onDismissed = function onDismissed() {\r\n");
      out.write("                        // Note: Prompt user to pay again or show an error page\r\n");
      out.write("                        console.log(\"Payment dismissed\");\r\n");
      out.write("                        window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\";\r\n");
      out.write("                    };\r\n");
      out.write("\r\n");
      out.write("                    // Error occurred\r\n");
      out.write("                    payhere.onError = function onError(error) {\r\n");
      out.write("                        // Note: show an error page\r\n");
      out.write("                        console.log(\"Error:\" + error);\r\n");
      out.write("                        alert(\"Process failed try again later.\")\r\n");
      out.write("                    };\r\n");
      out.write("\r\n");
      out.write("                    // Put the payment variables here\r\n");
      out.write("                    let payment = {\r\n");
      out.write("                        \"sandbox\": true,\r\n");
      out.write("                        \"merchant_id\": data.merchantId ?? \"\",    // Replace your Merchant ID\r\n");
      out.write("                        \"return_url\": \"\",     // Important\r\n");
      out.write("                        \"cancel_url\": \"\",     // Important\r\n");
      out.write("                        \"notify_url\": \"\",\r\n");
      out.write("                        \"order_id\": data.invoiceId ?? \"\",\r\n");
      out.write("                        \"items\": \"Cart\",\r\n");
      out.write("                        \"amount\": parseFloat(String(data.total ?? 0)).toFixed(2),\r\n");
      out.write("                        \"currency\": data.currency ?? \"\",\r\n");
      out.write("                        \"hash\": data.hash ?? \"\", // *Replace with generated hash retrieved from backend\r\n");
      out.write("                        \"first_name\": data.firstName ?? \"\",\r\n");
      out.write("                        \"last_name\": data.lastName ?? \"\",\r\n");
      out.write("                        \"email\": data.email ?? \"\",\r\n");
      out.write("                        \"phone\": data.contact ?? \"\",\r\n");
      out.write("                        \"address\": addressDetails.street ?? \"\",\r\n");
      out.write("                        \"city\": addressDetails.city ?? \"\",\r\n");
      out.write("                        \"country\": \"Sri Lanka\",\r\n");
      out.write("                        \"delivery_address\": addressDetails.street ?? \"\",\r\n");
      out.write("                        \"delivery_city\": addressDetails.city ?? \"\",\r\n");
      out.write("                        \"delivery_country\": \"Sri Lanka\",\r\n");
      out.write("                        \"custom_1\": \"\",\r\n");
      out.write("                        \"custom_2\": \"\"\r\n");
      out.write("                    };\r\n");
      out.write("\r\n");
      out.write("                    console.log(payment);\r\n");
      out.write("\r\n");
      out.write("                    // Show the payhere.js popup, when \"PayHere Pay\" is clicked\r\n");
      out.write("                    // document.getElementById('payhere-payment').onclick = function (e) {\r\n");
      out.write("                    payhere.startPayment(payment);\r\n");
      out.write("                    // };\r\n");
      out.write("\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"Missing Data on payment\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            function saveCartOrder(paymentData,addressDetails){\r\n");
      out.write("                if(paymentData && addressDetails){\r\n");
      out.write("                    let formData =  new FormData();\r\n");
      out.write("                    formData.append(\"invoiceId\",paymentData.invoiceId ?? \"\");\r\n");
      out.write("                    formData.append(\"payment_method\",addressDetails.paymentMethod ?? null);\r\n");
      out.write("                    formData.append(\"city\",addressDetails.city);\r\n");
      out.write("                    formData.append(\"street\",addressDetails.street);\r\n");
      out.write("                    formData.append(\"zipCode\",addressDetails.zipcode);\r\n");
      out.write("\r\n");
      out.write("                    secureFetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/orders/cart-checkout\",{\r\n");
      out.write("                        method:'post',\r\n");
      out.write("                        headers:'multipart/form-data',\r\n");
      out.write("                        body:formData\r\n");
      out.write("                    }).then(\r\n");
      out.write("                        async response =>{\r\n");
      out.write("                            if(response.ok){\r\n");
      out.write("                                return await response.json();\r\n");
      out.write("                            }else{\r\n");
      out.write("                                return null;\r\n");
      out.write("                            }\r\n");
      out.write("                        })\r\n");
      out.write("                        .then(async data=>{\r\n");
      out.write("                            if(data){\r\n");
      out.write("                                console.log(JSON.stringify(data));\r\n");
      out.write("                                alert(\"Order Placed Successfully\");\r\n");
      out.write("                                window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("                            }else{\r\n");
      out.write("                                alert(\"couldn't save Order Data\");\r\n");
      out.write("                                window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\";\r\n");
      out.write("                            }\r\n");
      out.write("                        })\r\n");
      out.write("\r\n");
      out.write("                }else\r\n");
      out.write("                    alert(\"Invalid Command\");\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function plusQuantity(itemId, quantity) {\r\n");
      out.write("                if (itemId && quantity && quantity) {\r\n");
      out.write("                    // alert(\"plus\");\r\n");
      out.write("                    updateQuantity(itemId, Number(quantity) + 1);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function minusQuantity(itemId, quantity) {\r\n");
      out.write("                if (itemId && quantity && quantity > 1) {\r\n");
      out.write("                    // alert(\"minus\");\r\n");
      out.write("                    updateQuantity(itemId, Number(quantity) - 1);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function updateQuantity(itemId, quantity) {\r\n");
      out.write("                const data = {\r\n");
      out.write("                    id: itemId,\r\n");
      out.write("                    quantity\r\n");
      out.write("                }\r\n");
      out.write("                console.log(\"REQUEST BODY :::\", data);\r\n");
      out.write("                secureFetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/cart/qty\", {\r\n");
      out.write("                    method: 'PATCH',\r\n");
      out.write("                    headers: {\r\n");
      out.write("                        'Content-Type': 'application/json'\r\n");
      out.write("                    },\r\n");
      out.write("                    body: JSON.stringify(data)\r\n");
      out.write("                })\r\n");
      out.write("                    .then(async response => {\r\n");
      out.write("                        if (response.ok) {\r\n");
      out.write("                            return await response.json();\r\n");
      out.write("                        }\r\n");
      out.write("                        return null;\r\n");
      out.write("                    })\r\n");
      out.write("                    .then(async data => {\r\n");
      out.write("                        if (data)\r\n");
      out.write("                            fetchCartData();\r\n");
      out.write("                        else\r\n");
      out.write("                            alert(\"Quantity update failed\");\r\n");
      out.write("                    });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function removeItemFromCart(itemId){\r\n");
      out.write("                if(itemId){\r\n");
      out.write("                    secureFetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/cart\"+itemId,{\r\n");
      out.write("                        method: 'DELETE',\r\n");
      out.write("                    })\r\n");
      out.write("                        .then(async response =>{\r\n");
      out.write("                            if(response.ok){\r\n");
      out.write("                                return await response.json();\r\n");
      out.write("                            }\r\n");
      out.write("                            return null;\r\n");
      out.write("                        })\r\n");
      out.write("                        .then(async data=>{\r\n");
      out.write("\r\n");
      out.write("                            if(data){\r\n");
      out.write("                                fetchCartData();\r\n");
      out.write("                            }else{\r\n");
      out.write("                                alert(\"Cart Removal Failed\");\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                        });\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function clearMyCart(){\r\n");
      out.write("                secureFetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/clear-my-cart\",{\r\n");
      out.write("                    method:'DELETE'\r\n");
      out.write("                })\r\n");
      out.write("                    .then(async response=>{\r\n");
      out.write("                        if(response.ok)\r\n");
      out.write("                            return await response.json();\r\n");
      out.write("\r\n");
      out.write("                        return null;\r\n");
      out.write("                    }).then(async data=>{\r\n");
      out.write("                        if(data)\r\n");
      out.write("                            fetchCartData();\r\n");
      out.write("                        else\r\n");
      out.write("                            alert(\"Cart Clear Failed\");\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
