/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2025-01-15 12:15:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class store_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244278716L));
    _jspx_dependants.put("jar:file:/C:/Users/Yasiru%20Kavinda/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/store.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/store.jsp(4,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/store.jsp(118,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("script");
      // /WEB-INF/views/frontend/store.jsp(118,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setType("REPLACE");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <!-- Single Page Header start -->\r\n");
      out.write("        <div class=\"container-fluid page-header py-5\">\r\n");
      out.write("            <h1 class=\"text-center text-white display-6\">Shop</h1>\r\n");
      out.write("            <ol class=\"breadcrumb justify-content-center mb-0\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">Pages</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active text-white\">Shop</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Single Page Header End -->\r\n");
      out.write("        <!-- Fruits Shop Start-->\r\n");
      out.write("        <div class=\"container-fluid fruite py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <h1 class=\"mb-4\">Product Catalogue</h1>\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"row g-4\">\r\n");
      out.write("                            <div class=\"col-xl-3\">\r\n");
      out.write("                                <div class=\"input-group w-100 mx-auto d-flex\">\r\n");
      out.write("                                    <input type=\"search\" class=\"form-control p-3\" placeholder=\"keywords\"\r\n");
      out.write("                                           aria-describedby=\"search-icon-1\" id=\"search-key\" onkeyup=\"onKeywordChanges();\">\r\n");
      out.write("                                    <span id=\"search-icon-1\" class=\"input-group-text p-3\" onclick=\"setKeywords()\"><i\r\n");
      out.write("                                            class=\"fa fa-search\"></i></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-6\"></div>\r\n");
      out.write("                            <div class=\"col-xl-3\">\r\n");
      out.write("                                <div class=\"bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4\">\r\n");
      out.write("                                    <label for=\"filterFormatType\">Default Sorting:</label>\r\n");
      out.write("                                    <select name=\"orderby\" class=\"border-0 form-select-sm bg-light me-3\" id=\"filterFormatType\"\r\n");
      out.write("                                            onchange=\"onChangeFilters()\">\r\n");
      out.write("                                        <option value=null selected=\"selected\">-Select-</option>\r\n");
      out.write("                                        <option value=\"A_Z\">A to Z</option>\r\n");
      out.write("                                        <option value=\"Z_A\">Z to A</option>\r\n");
      out.write("                                        <option value=\"LATEST\">Latest</option>\r\n");
      out.write("                                        <option value=\"L_H\">Price: low to high</option>\r\n");
      out.write("                                        <option value=\"H_L\">Price: high to low</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row g-4\">\r\n");
      out.write("                            <div class=\"col-lg-3\">\r\n");
      out.write("                                <div class=\"row g-4\">\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <div class=\"mt-5 mb-3\">\r\n");
      out.write("                                            <h4>Categories</h4>\r\n");
      out.write("                                            <ul class=\"list-unstyled fruite-categorie\" id=\"categoryList\">\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <div class=\"d-flex justify-content-between fruite-name\">\r\n");
      out.write("                                                        <a href=\"#\"><i class=\"fas fa-apple-alt me-2\"></i>Apples</a>\r\n");
      out.write("                                                        <span>(3)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-9\">\r\n");
      out.write("                                <div class=\"row g-4 justify-content-center\" id=\"productList\">\r\n");
      out.write("                                        ");
      out.write("\r\n");
      out.write("                                    <div class=\"col-md-6 col-lg-6 col-xl-4\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                <img src=\"img/fruite-item-5.jpg\" class=\"img-fluid w-100 rounded-top\"\r\n");
      out.write("                                                     alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\"\r\n");
      out.write("                                                 style=\"top: 10px; left: 10px;\">Fruits\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>Grapes</h4>\r\n");
      out.write("                                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do\r\n");
      out.write("                                                    eiusmod te incididunt</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">$4.99 / kg</p>\r\n");
      out.write("                                                    <a href=\"#\"\r\n");
      out.write("                                                       class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i\r\n");
      out.write("                                                            class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to\r\n");
      out.write("                                                        cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"row g-4 justify-content-center\">\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <div class=\"pagination d-flex justify-content-center mt-5\" id=\"pagination-box\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Fruits Shop End-->\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            let totalPageCount = 0;\r\n");
      out.write("            let totalElements = 0;\r\n");
      out.write("            let keywords = \"\";\r\n");
      out.write("            let maxPrice = 0;\r\n");
      out.write("            let selectedCategory = null;\r\n");
      out.write("            let selectBrand = null;\r\n");
      out.write("            let resultSorter = null;\r\n");
      out.write("            let pageSize = 6;\r\n");
      out.write("            let pageNo = 1;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            function openSingleProductView(id){\r\n");
      out.write("               const url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("single-product/{stock_id}\";\r\n");
      out.write("               window.location.href = url.replace(\"{stock_id}\",id);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            const setKeywords = () => {\r\n");
      out.write("                keywords = document.getElementById(\"search-key\").value;;\r\n");
      out.write("                search();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const setSelectedCategory = (id)=>{\r\n");
      out.write("               selectedCategory = id == \"null\" ? null :id;\r\n");
      out.write("               document.getElementById(\"categoryList\").value = selectedCategory;\r\n");
      out.write("               console.log(selectedCategory);\r\n");
      out.write("               search();\r\n");
      out.write("            }\r\n");
      out.write("            const setSorting = (order)=>{\r\n");
      out.write("                resultSorter = order == \"null\"?null:order;\r\n");
      out.write("                search();\r\n");
      out.write("            }\r\n");
      out.write("            const setPageNo = (number) => {\r\n");
      out.write("                pageNo = Number(number);\r\n");
      out.write("                search();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            loadCategories();\r\n");
      out.write("            search();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            async function loadCategories() {\r\n");
      out.write("                const categoryList = document.getElementById(\"categoryList\");\r\n");
      out.write("\r\n");
      out.write("                categoryList.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("                categoryList.innerHTML += \"<li> <div class=\"+\"d-flex justify-content-between fruite-name\"+\">\" +\r\n");
      out.write("                    \"                                    <a href='javascript:;' onclick='onChangeSelectedCategory(\"+\"null\"+\",false)'><i class=\"+\"fas fa-apple-alt me-2\"+\"></i>All Categories</a> </div></li>\";\r\n");
      out.write("\r\n");
      out.write("                await fetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/categories\").then(async resp =>{\r\n");
      out.write("                    if(resp.ok){\r\n");
      out.write("                        return await resp.json();\r\n");
      out.write("                    }\r\n");
      out.write("                    return null;\r\n");
      out.write("                }).then(async data=>{\r\n");
      out.write("                    if(data){\r\n");
      out.write("                        if(data?.data?.length > 0){\r\n");
      out.write("                            data.data.map((category)=>{\r\n");
      out.write("                                categoryList.innerHTML += \"<li> <div class=\"+\"d-flex justify-content-between fruite-name\"+\">\" +\r\n");
      out.write("                                    \"                                    <a href='javascript:;' onclick='onChangeSelectedCategory(\"+category.id+\",false)'><i class=\"+\"fas fa-apple-alt me-2\"+\"></i>\"+category?.name ?? '' + \"</a>\";\r\n");
      out.write("                            });\r\n");
      out.write("                        }else{\r\n");
      out.write("                            console.log(\"Empty Category List\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }else {\r\n");
      out.write("                        console.log(\"Error Loading Data\");\r\n");
      out.write("                    }\r\n");
      out.write("                })\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            async function search(){\r\n");
      out.write("                const productList = document.getElementById(\"productList\");\r\n");
      out.write("                productList.innerHTML = \"\";\r\n");
      out.write("                let query = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/stock/search?pageNo=\"+pageNo+\"&pageSize=\"+pageSize;\r\n");
      out.write("\r\n");
      out.write("                if(keywords)\r\n");
      out.write("                    query += \"&key=\"+keywords;\r\n");
      out.write("                if(selectedCategory)\r\n");
      out.write("                    query += \"&category=\"+selectedCategory;\r\n");
      out.write("                if(resultSorter)\r\n");
      out.write("                    query += \"&sortBy=\"+resultSorter;\r\n");
      out.write("\r\n");
      out.write("                console.log(query);\r\n");
      out.write("                await fetch(query)\r\n");
      out.write("                    .then(async response=>{\r\n");
      out.write("                       if(response.ok){\r\n");
      out.write("                           return await response.json();\r\n");
      out.write("                       }\r\n");
      out.write("                        return null;\r\n");
      out.write("                    })\r\n");
      out.write("                    .then(async data=>{\r\n");
      out.write("                        if(data?.data?.length>0){\r\n");
      out.write("                            totalPageCount = data?.totalPages;\r\n");
      out.write("                            data.data.map((item)=>{\r\n");
      out.write("\r\n");
      out.write("                                const cardTemplate = ` <div class=\"col-md-6 col-lg-6 col-xl-4\" onClick=\" openSingleProductView(`+item?.id+`)\">\r\n");
      out.write("                                        <div class=\"rounded position-relative fruite-item\">\r\n");
      out.write("                                            <div class=\"fruite-img\">\r\n");
      out.write("                                                  `+(item?.productByProductId?.images?.[0]? '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'+item?.productByProductId?.images?.[0]+'\" class=\"img-fluid w-100 rounded-top\" alt=\"Stock\"/>':'')+`\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"text-white bg-secondary px-3 py-1 rounded position-absolute\"\r\n");
      out.write("                                                 style=\"top: 10px; left: 10px;\">`+(item?.productByProductId?.categoriesByCategoriesId?.name)+`\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"p-4 border border-secondary border-top-0 rounded-bottom\">\r\n");
      out.write("                                                <h4>`+(item?.productByProductId?.name)+`</h4>\r\n");
      out.write("                                                <p>`+(item?.productByProductId?.description)+' '+(item?.productByProductId?.categoriesByCategoriesId?.name)+`</p>\r\n");
      out.write("                                                <div class=\"d-flex justify-content-between flex-lg-wrap\">\r\n");
      out.write("                                                    <p class=\"text-dark fs-5 fw-bold mb-0\">Rs.`+(item?.price)+`/ kg</p>\r\n");
      out.write("                                                    <a href=\"javascript:;\" onclick=\"addToCart(`+item.id+`)\"\r\n");
      out.write("                                                       class=\"btn border border-secondary rounded-pill px-3 text-primary\"><i\r\n");
      out.write("                                                            class=\"fa fa-shopping-bag me-2 text-primary\"></i> Add to cart</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>`;\r\n");
      out.write("                                productList.innerHTML += cardTemplate;\r\n");
      out.write("                            });\r\n");
      out.write("\r\n");
      out.write("                            setupPagination(data?.totalPages ?? 0, data?.totalElements ?? 0);\r\n");
      out.write("                        }else\r\n");
      out.write("                            totalPageCount = 0;\r\n");
      out.write("                    });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            function setupPagination(totalPages = 0, elementCount = 0){\r\n");
      out.write("                const page_number_box = document.getElementById(\"pagination-box\");\r\n");
      out.write("                page_number_box.innerHTML =  \"\";\r\n");
      out.write("\r\n");
      out.write("                let view = \"\";\r\n");
      out.write("                if(totalPages>0 && elementCount > 0){\r\n");
      out.write("                    if(pageNo>1){\r\n");
      out.write("                        view +=\r\n");
      out.write("                            `\r\n");
      out.write("                             <a href=\"#\" class=\"rounded\" onclick=\"decrementPageNo();\" \">&laquo;</a>\r\n");
      out.write("                            `\r\n");
      out.write("                    }\r\n");
      out.write("                    for(let i = 1; i<= totalPages; i++){\r\n");
      out.write("                        view += `\r\n");
      out.write("                           <a href=\"#\" class=\"`+(pageNo == i ? 'active':'')+` rounded\" href=\"javascript:;\" onclick=\"setPageNo(`+i+`)\">`+i+`</a>\r\n");
      out.write("                        `;\r\n");
      out.write("                    }\r\n");
      out.write("                    if(pageNo<totalPages){\r\n");
      out.write("                        view +=\r\n");
      out.write("                            `\r\n");
      out.write("                             <a href=\"#\" class=\"rounded\" onclick=\"incrementPageNo();\">&raquo;</a>\r\n");
      out.write("                            `\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    page_number_box.innerHTML =  view ;\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function addToCart(id){\r\n");
      out.write("                const data = {\r\n");
      out.write("                   stockId:id,\r\n");
      out.write("                    quantity:1,\r\n");
      out.write("                };\r\n");
      out.write("                secureFetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("api/v1/cart/add\",{\r\n");
      out.write("                    method: 'post',\r\n");
      out.write("                    headers:{\r\n");
      out.write("                        'Content-Type':'application/json'\r\n");
      out.write("                    },\r\n");
      out.write("                    body:JSON.stringify(data)\r\n");
      out.write("                }).then(async response=>{\r\n");
      out.write("                    if(response.ok){\r\n");
      out.write("                        return await response.json();\r\n");
      out.write("                    }\r\n");
      out.write("                    return null;\r\n");
      out.write("                })\r\n");
      out.write("                    .then(async data =>{\r\n");
      out.write("                        if(data){\r\n");
      out.write("                            alert(\"Item added to Cart\");\r\n");
      out.write("                            window.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\";\r\n");
      out.write("                        }else{\r\n");
      out.write("                            alert(\"Failed to Add to Cart\");\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            const onChangeSelectedCategory = (element, isElement = true) => {\r\n");
      out.write("                setSelectedCategory(isElement ? document.getElementById(element).value : element);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const onKeywordChanges = ()=>{\r\n");
      out.write("                setKeywords(document.getElementById(\"search-key\").value ?? null);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const onChangeSorting = ()=>{\r\n");
      out.write("                setSorting(document.getElementById(\"filterFormatType\").value);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const incrementPageNo = () => {\r\n");
      out.write("                if (pageNo < totalPageCount)\r\n");
      out.write("                    pageNo++;\r\n");
      out.write("                search();\r\n");
      out.write("            }\r\n");
      out.write("            const decrementPageNo = () => {\r\n");
      out.write("                if (pageNo > 1)\r\n");
      out.write("                    pageNo--;\r\n");
      out.write("                search();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
