#Server Details
server.port=8080
#
#Mail Service Details
mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=daab87c5ec1cfc
mail.password=67205eef70292a
app.mail=info@nf.com
#
#JWT Details
jwt.secret=0q@S6N%0(1$rT9i:A2%Xtmbq$@TQ&Ft@:TK7Vc(=FPfrMDh!
# 5 minutes
jwt.accessTokenLife=500
# 7 days
jwt.refreshTokenLife=10080
#
#file Upload Details
archive.path=/uploads

#Payhere Gateway
payhere.merchant.id=1229313
payhere.merchant.secret=MzAyOTcyNTU3NTQxMjk4Nzk5NDAyMTk4MTY5NjQ2NjAyMzc5MjMx